# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77ffb77155c5ae875e3522052032f4e12e65589a2850666144b8b1d07b879fa33cea098b4fe86b6f63b4838c6ec6340c2676244975c0f6fd7b9bfab9b4e0fdc7

test:
  secret_key_base: 9fb905983e77d037b4526e1ead7d03f87c92853f12a3923eca2a92361bb03159ccedb99262ba96c97e9f1b43f8dfa6bbd3894f3e0058ffe6668b0e0c055e823a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
